---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: "Remove the dependencies that are no longer required"
  become: yes
  apt:
    autoremove: yes

- name: "Install dependecies"
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "Install pm"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present