---
- name: Create app directory
  file:
    path: $HOME/web
    state: directory

- name: "Extract artifacts"
    become: true
    copy:
      src: "files/artifact.tar.gz"
      dest: "$HOME/web/"

- name: "Install dependecies"
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes
    
- name: "Install pm"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: "Install Dependencies"
  become: true
  shell: |
    tar -xvf artifact.tar.gz .
    rm artifact.tar.gz
    npm 

- name: "Where are we"
  become: true
  shell: |
    pwd && ls -la & echo "May be we are here"
    cd web
    ls -a

- name: "Start Server"
  become: true
  shell: |
    cd ~/web/
    sudo pm2 stop default 
    sudo pm2 start npm -- run start
  register: web



