---
- name: Create app directory
  file:
    path: $HOME/web
    state: directory

- name: "Copy files to server"
  ansible.builtin.copy:
    src: "files/artifact.tar.gz"
    dest: "$HOME/artifact.tar.gz"

- name: "Install dependecies"
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes
    
- name: "Install pm"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: "Install Dependencies"
  become: true
  shell: |
    tar -xvf artifact.tar.gz .
    rm artifact.tar.gz
    npm install
- name: "Start Server"
  become: true
  shell: |
    sudo pm2 stop default 
    sudo pm2 start npm -- run start 


