---
- name: Create app directory
  file:
    path: ~/backend-app
    state: directory

- name: "Extract tar/zip file"
  become: true
  unarchive:
    src: ~/project/artifact.tar.gz
    dest: ~/backend-app/

- name: "Install dependecies"
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes
    
- name: "Install pm"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: "Install backend dependecies"
  become: yes
  shell: |
    cd ~/backend-app/
    npm install

- name: "Where are we"
  become: true
  shell: |
    pwd && ls -la && echo "May be we are here"
    cd ~/backend-app/
    ls -a

- name: "Start Server"
  become: true
  shell: |
    cd ~/backend-app/
    sudo pm2 stop default 
    sudo pm2 start npm -- run start
  register: web
  
- debug:
    msg: "{{ web.stdout_lines }}"



